"""empty message

Revision ID: 0a04ded5a013
Revises: 89b24179dfab
Create Date: 2020-08-08 02:53:08.109415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a04ded5a013'
down_revision = '89b24179dfab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('donations_donator_id_fkey', 'donations', type_='foreignkey')
    op.drop_column('donations', 'donator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('donator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('donations_donator_id_fkey', 'donations', 'donors', ['donator_id'], ['id'])
    # ### end Alembic commands ###
