"""empty message

Revision ID: d110e70d0d3e
Revises: 0a04ded5a013
Create Date: 2020-08-08 02:54:18.877797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd110e70d0d3e'
down_revision = '0a04ded5a013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('donor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'donations', 'donors', ['donor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_column('donations', 'donor_id')
    # ### end Alembic commands ###
